language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build

notifications:
  slack: myspace-wez3757:OeiMPP2SmMt3UYWGn9L4XK4E
  email:
    recipients:
      - diegoandresrojas2000@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-page
  commit_message: 'Deploy del proyecto'
  on:
    branch: master
